# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pastorius Beehive
email: nelsd@sas.upenn.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Pastorius Beehive Project creates a working digital edition of Francis Daniel Pastorius' Beehive Manuscript.
baseurl: "/digital-beehive" # the subpath of your site, e.g. /blog
url: "https://KislakCenter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /img/logo.png
github_username:  drnelson6

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

permalink: 'pretty'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Configure the collections. Must do before running wax tasks in the command line.

collections:
  exhibits:
    output: true
  alpha1:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha1.csv
  alpha2:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha2.csv
  alpha3:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha3.csv
  alpha4:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha4.csv
  alpha5:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha5.csv
  index1:
    output: true
    layout: 'index_item'
    metadata:
      source: index1.csv
  index2:
    output: true
    layout: 'index_item'
    metadata:
      source: index2.csv
  index3:
    output: true
    layout: 'index_item'
    metadata:
      source: index3.csv
  index4:
    output: true
    layout: 'index_item'
    metadata:
      source: index4.csv
  index5:
    output: true
    layout: 'index_item'
    metadata:
      source: index5.csv
  toc_vol1:
    output: true
    layout: 'toc1_item'
    metadata:
      source: toc_vol1.csv
  toc_vol2:
    output: true
    layout: 'toc2_item'
    metadata:
      source: toc_vol2.csv
  toc_vol3:
    output: true
    layout: 'toc3_item'
    metadata:
      source: toc_vol3.csv
  toc:
    output: true
    layout: 'toc_item'
    metadata:
      source: master_toc.csv

# Configure the search function
# Can make multiple indices, but Wax recommends against it.

search:
  main:
    index: '/search/index.json'
    collections:
      alpha1:
        content: false
        fields:
          - image_number
          - label
          - topic
          - xref
          - index
      alpha2:
        content: false
        fields:
          - image_number
          - label
          - topic
          - xref
          - index
      alpha3:
        content: false
        fields:
          - image_number
          - label
          - topic
          - xref
          - index
      alpha4:
        content: false
        fields:
          - image_number
          - label
          - topic
          - xref
          - index
      alpha5:
        content: false
        fields:
          - image_number
          - label
          - topic
          - xref
          - index
      index1:
        content: false
        fields:
          - image_number
          - label
          - entry
          - see
      index2:
        content: false
        fields:
          - image_number
          - label
          - entry
          - see
      index3:
        content: false
        fields:
          - image_number
          - label
          - entry
          - see
      index4:
        content: false
        fields:
          - image_number
          - label
          - entry
          - see
      index5:
        content: false
        fields:
          - image_number
          - label
          - entry
          - see

# site menu settings

menu:
  - label: 'About'
    sub:
      - label: 'The Project'
        link: '/about/'
      #- label: 'Documentation'
      #   link: Link here to the Github
      - label: 'Documentation'
        link: '/documentation/'
  - label: 'Browse the Book'
    sub:
      - label: 'Browse by Page'
        link: '/pagebrowse/'
      - label:  'Browse by Section'
        link: '/sectionbrowse/'
  - label: 'Linked Entries'
    sub:
      - label: 'Alphabetical Section'
        link: '/alphabetical/'
      - label: 'Index'
        link: '/index/'
  - label: Search
    link: '/search/'

# site footer settings

footer:
  links:
    - label: 'Github'
      link: 'https://github.com/KislakCenter/digital-beehive'
    - label: 'University of Pennsylvania Libraries'
      link: 'https://www.library.upenn.edu'
    - label: 'Kislak Center for Special Collections, Rare Books and Manuscripts'
      link: 'https://www.library.upenn.edu/kislak'
