# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Beehive
email: nelsd@sas.upenn.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Digital Beehive Project creates a working digital edition of Francis Daniel Pastorius' Beehive Manuscript.
baseurl: "/digital-beehive" # the subpath of your site, e.g. /blog
url: "https://KislakCenter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /img/logo.png
github_username:  drnelson6

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

permalink: 'pretty'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Configure the collections. Must do before running wax tasks in the command line.

collections:
  exhibits:
    output: true
  alpha1:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha1.csv
  alpha2:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha2.csv
  alpha3:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha3.csv
  alpha4:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha4.csv
  alpha5:
    output: true
    layout: 'alpha_item'
    metadata:
      source: alpha5.csv
  index1:
    output: true
    layout: 'index_item'
    metadata:
      source: index1.csv
  index2:
    output: true
    layout: 'index_item'
    metadata:
      source: index2.csv
  index3:
    output: true
    layout: 'index_item'
    metadata:
      source: index3.csv
  index4:
    output: true
    layout: 'index_item'
    metadata:
      source: index4.csv
  index5:
    output: true
    layout: 'index_item'
    metadata:
      source: index5.csv
  num1:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num1.csv
  num2:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num2.csv
  num3:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num3.csv
  num4:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num4.csv
  num5:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num5.csv
  num6:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num6.csv
  num7:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num7.csv
  num8:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num8.csv
  num9:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num9.csv
  num10:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num10.csv
  num11:
    output: true
    layout: 'alpha_item'
    metadata:
      source: num11.csv
  toc:
    output: true
    layout: 'toc_item'
    metadata:
      source: master_toc.csv

# beehive futures: add collection for transcriptions (short term)
# beehive futures: modify ruby code for wax so that transcriptions are
# automatically included as content on wax pages for toc (long term)

# Configure the search function
# Can make multiple indices, but Wax recommends against it.

search:
  main:
    index: '/search/index.json'
    collections:
      alpha1:
        content: false
        fields:
          - label
          - topic
          - xref
          - index
      alpha2:
        content: false
        fields:
          - label
          - topic
          - xref
          - index
      alpha3:
        content: false
        fields:
          - label
          - topic
          - xref
          - index
      alpha4:
        content: false
        fields:
          - label
          - topic
          - xref
          - index
      alpha5:
        content: false
        fields:
          - label
          - topic
          - xref
          - index
      index1:
        content: false
        fields:
          - label
          - entry
          - see
      index2:
        content: false
        fields:
          - label
          - entry
          - see
      index3:
        content: false
        fields:
          - label
          - entry
          - see
      index4:
        content: false
        fields:
          - label
          - entry
          - see
      index5:
        content: false
        fields:
          - label
          - entry
          - see
      num1:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num2:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num3:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num4:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num5:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num6:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num7:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num8:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num9:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num10:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index
      num11:
        content: false
        fields:
          - label
          - entry
          - topic
          - xref
          - index

# beehive futures: modify ruby code to automatically clean up search

# site menu settings

menu:
  - label: 'About'
    sub:
      - label: 'The Project'
        link: '/about/'
      - label: 'Technical Documentation'
        link: '/documentation/'
      - label: 'Data Model'
        link: 'data-model/'
      - label: 'Project Data'
        link: 'data/' 
      - label: 'Contact'
        link: '/contact/'
  - label: 'Contents'
    sub:
      - label: 'Introduction'
        link: '/pagebrowse/'
      - label: 'Volume One'
        link: '/tocvol1/'
      - label: 'Volume Two'
        link: '/tocvol2/'
      - label: 'Octavo Index'
        link: '/tocvol3/'
      - label:  'Sections'
        link: '/sectionbrowse/'
      - label: 'Physical Features'
        link: '/tocphysical/'
  - label: 'Browse Entries'
    sub:
      - label: 'Alphabetical Section'
        link: '/alphabetical/'
      - label: 'Numerical Section'
        link: '/numerical/'
      - label: 'Octavo Index'
        link: '/index/'
  - label: 'Further Reading'
    sub:
      - label: 'Bibliography'
        link: '/bibliography/'
      - label: 'Beehive Diary'
        link: '/making-the-beehive/'
      - label: 'Book List'
        link: '/book-list/'
  - label: Search
    link: '/search/'

# site footer settings

footer:
  links:
    - label: 'Github'
      link: 'https://github.com/KislakCenter/digital-beehive'
    - label: 'University of Pennsylvania Libraries'
      link: 'https://www.library.upenn.edu'
    - label: 'Kislak Center for Special Collections, Rare Books and Manuscripts'
      link: 'https://www.library.upenn.edu/kislak'
