# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pastorius Beehive
email: nelsd@sas.upenn.edu
description: >- # this means to ignore newlines until "baseurl:"
  The Pastorius Beehive Project creates a working digital edition of Francis Daniel Pastorius' Beehive Manuscript.
baseurl: "/New_Beehive" # the subpath of your site, e.g. /blog
url: "https://drnelson6.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# copyright: 'Insert Copyright'
logo: /img/logo.png
github_username:  drnelson6

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: 'pretty'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  exhibits:
    output: true
  alphabetical: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'alpha_item' # the layout for the pages to use
    metadata:
      source: 'alpha_test.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/alpha' # path to the directory of images within `_data`

menu:
  - label: 'About'
    sub:
      - label: 'The Project'
        link: '/about/'
      #- label: 'Documentation'
      #   link: Link here to the Github
      - label: 'Credits'
        link: '/credits/'
  - label: 'Browse'
    sub:
      - label: 'Table of Contents'
        link: '/toc/'
      - label: 'Alphabetical Section'
        link: '/alphabetical/'
      - label: 'Index'
        link: '/Index/'
  - label: 'Blog'
    link: '/blog/'
